### ISSUE TITLE
Style

### ISSUE THREAD

**Issue by kaparray** [kaparray/Velp#2]
Style

**Comment by kaparray** [comment]
<img width="255" alt="2018-02-03 17 14 54" src="https://user-images.githubusercontent.com/31259204/35767939-dc1f415c-0905-11e8-8dc1-bc3fc15b8e96.png">

**Comment by kaparray** [comment]
![ic_launcher-web](https://user-images.githubusercontent.com/31259204/35996088-7f68a050-0d26-11e8-8ec8-ed7d29299c98.png)

**Comment by lordcoudy** [comment]
I made some cosmetic changes in strings and text on buttons. Shall I commit them?
