### ISSUE TITLE
Add in project this

### ISSUE THREAD

**Issue by kaparray** [kaparray/Velp#3]
<img width="162" alt="2018-02-08 22 53 27" src="https://user-images.githubusercontent.com/31259204/35994981-15bcf032-0d23-11e8-9815-3166c9f0b0e4.png">

**Comment by kaparray** [comment]
I add DataBase NoSQL in fire base(JSON)

**Comment by kaparray** [comment]
This is DataBase 
<img width="448" alt="2018-02-08 22 56 26" src="https://user-images.githubusercontent.com/31259204/35995071-5b3aac12-0d23-11e8-892d-90869fa24453.png">

**Comment by kaparray** [comment]
Maybe after change name in others field

**Comment by kaparray** [comment]
And I testing Firebase function!!! This is real shit 🔥🔥🔥 I don like JavaScript!!! You know JS???

**Comment by deissh** [comment]
Привет, в чем проблема JS? Могу подсказать если нужно.

**Comment by deissh** [comment]
Так же лучше изначально написать Back-End (API) для приложения, это позволит в бушующим не перестраивать всю логику работы приложения.
